# Generated by Django 3.2.9 on 2022-02-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=49)),
                ('phone', models.CharField(max_length=14)),
                ('subject', models.CharField(max_length=144)),
                ('desc', models.TextField()),
            ],
        ),
    ]
